# See:
#   https://colosseumneu.freshdesk.com/support/solutions/articles/61000253508-traffic-generation
- name: Install packages needed to build mgen
  apt:
    state: present
    pkg:
      - g++-5
      - libpcap-dev

- name: Copy mgen source
  unarchive:
      src: https://github.com/USNavalResearchLaboratory/mgen/releases/download/v5.02c/src-mgen-with-protolib-5.02c.tgz
      dest: /tmp
      remote_src: yes

- name: Build mgen
  shell: make -f Makefile.linux CC=g++-5
  args:
    chdir: /tmp/src-mgen-5.02c/makefiles

- name: Install mgen
  shell: cp /tmp/src-mgen-5.02c/makefiles/{{item}} /usr/local/bin
  with_items:
    - mgen
    - mpmgr

- name: Remove mgen leftovers
  file:
    state: absent
    path: /tmp/{{item}}
  with_items:
    - src-mgen-5.02c
