- hosts: localhost
  connection: local
  roles:
    - role: lxd-create-containers
      containers:
        - dragonradio-2004-base

- hosts: dragonradio-2004-base
  connection: local
  become: false
  roles:
    - update
    - base
    - dragonradio-base
    - passwd
    - colosseum-cli
    - role: gpsd
      version: 3.21
    - role: protobuf
      version: 3.13.0
    - clean

- hosts: localhost
  connection: local
  roles:
    - role: lxd-export-containers
      containers:
        - dragonradio-2004-base
      lxd_export_dir: ../../images
